spring:
  application:
    name: graphqljava

  jpa:
    hibernate:
      ddl-auto: create-drop #dont do this in production
    show-sql: true

  graphql:
    graphiql:
      enabled: true

  threads:
    virtual:
      enabled: true

management:
  tracing:
    sampling:
      probability: 1.0 #dont do this in production can make down